# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home23/noeleel/NAO-Foot-Equipe-X/py/team_LeLamaJ/InterfaceNAO.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IHM(object):
    def setupUi(self, IHM):
        IHM.setObjectName(_fromUtf8("IHM"))
        IHM.resize(915, 716)
        self.centralwidget = QtGui.QWidget(IHM)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 401, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.Conteneur = QtGui.QWidget(self.centralwidget)
        self.Conteneur.setGeometry(QtCore.QRect(20, 40, 881, 451))
        self.Conteneur.setObjectName(_fromUtf8("Conteneur"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 500, 179, 134))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.Bouton_rightturn = QtGui.QPushButton(self.layoutWidget)
        self.Bouton_rightturn.setObjectName(_fromUtf8("Bouton_rightturn"))
        self.verticalLayout_2.addWidget(self.Bouton_rightturn)
        self.Bouton_rightshoot = QtGui.QPushButton(self.layoutWidget)
        self.Bouton_rightshoot.setObjectName(_fromUtf8("Bouton_rightshoot"))
        self.verticalLayout_2.addWidget(self.Bouton_rightshoot)
        self.Bouton_rightshift = QtGui.QPushButton(self.layoutWidget)
        self.Bouton_rightshift.setObjectName(_fromUtf8("Bouton_rightshift"))
        self.verticalLayout_2.addWidget(self.Bouton_rightshift)
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(430, 500, 113, 134))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.Bouton_forward = QtGui.QPushButton(self.layoutWidget_2)
        self.Bouton_forward.setObjectName(_fromUtf8("Bouton_forward"))
        self.verticalLayout_3.addWidget(self.Bouton_forward)
        self.Bouton_back = QtGui.QPushButton(self.layoutWidget_2)
        self.Bouton_back.setObjectName(_fromUtf8("Bouton_back"))
        self.verticalLayout_3.addWidget(self.Bouton_back)
        self.Bouton_crouch = QtGui.QPushButton(self.layoutWidget_2)
        self.Bouton_crouch.setObjectName(_fromUtf8("Bouton_crouch"))
        self.verticalLayout_3.addWidget(self.Bouton_crouch)
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(570, 500, 123, 134))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.Bouton_start = QtGui.QPushButton(self.layoutWidget_3)
        self.Bouton_start.setObjectName(_fromUtf8("Bouton_start"))
        self.verticalLayout_4.addWidget(self.Bouton_start)
        self.Bouton_stop = QtGui.QPushButton(self.layoutWidget_3)
        self.Bouton_stop.setObjectName(_fromUtf8("Bouton_stop"))
        self.verticalLayout_4.addWidget(self.Bouton_stop)
        self.Bouton_quitter = QtGui.QPushButton(self.layoutWidget_3)
        self.Bouton_quitter.setObjectName(_fromUtf8("Bouton_quitter"))
        self.verticalLayout_4.addWidget(self.Bouton_quitter)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 500, 187, 134))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.Bouton_leftturn = QtGui.QPushButton(self.widget)
        self.Bouton_leftturn.setObjectName(_fromUtf8("Bouton_leftturn"))
        self.verticalLayout.addWidget(self.Bouton_leftturn)
        self.Bouton_leftshoot = QtGui.QPushButton(self.widget)
        self.Bouton_leftshoot.setObjectName(_fromUtf8("Bouton_leftshoot"))
        self.verticalLayout.addWidget(self.Bouton_leftshoot)
        self.Bouton_leftshift = QtGui.QPushButton(self.widget)
        self.Bouton_leftshift.setObjectName(_fromUtf8("Bouton_leftshift"))
        self.verticalLayout.addWidget(self.Bouton_leftshift)
        IHM.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(IHM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        IHM.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(IHM)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        IHM.setStatusBar(self.statusbar)
        self.actionCommencer_Ctrl_C = QtGui.QAction(IHM)
        self.actionCommencer_Ctrl_C.setObjectName(_fromUtf8("actionCommencer_Ctrl_C"))
        self.actionAide_Ctrl_A = QtGui.QAction(IHM)
        self.actionAide_Ctrl_A.setObjectName(_fromUtf8("actionAide_Ctrl_A"))
        self.actionDocumentation_Ctrl_D = QtGui.QAction(IHM)
        self.actionDocumentation_Ctrl_D.setObjectName(_fromUtf8("actionDocumentation_Ctrl_D"))
        self.actionQuitter_Ctrl_Q = QtGui.QAction(IHM)
        self.actionQuitter_Ctrl_Q.setObjectName(_fromUtf8("actionQuitter_Ctrl_Q"))
        self.menuMenu.addAction(self.actionCommencer_Ctrl_C)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionDocumentation_Ctrl_D)
        self.menuMenu.addAction(self.actionAide_Ctrl_A)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuitter_Ctrl_Q)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(IHM)
        QtCore.QObject.connect(self.Bouton_quitter, QtCore.SIGNAL(_fromUtf8("clicked()")), IHM.close)
        QtCore.QObject.connect(self.actionQuitter_Ctrl_Q, QtCore.SIGNAL(_fromUtf8("triggered()")), IHM.close)
        QtCore.QMetaObject.connectSlotsByName(IHM)

    def retranslateUi(self, IHM):
        IHM.setWindowTitle(_translate("IHM", "NAO Football Game LELAMAJ", None))
        self.label.setText(_translate("IHM", "Fenêtre de visualisation du robot NAO de l\'équipe LELAMAJ", None))
        self.label_3.setText(_translate("IHM", "Droite", None))
        self.Bouton_rightturn.setText(_translate("IHM", "Tourner(Droite)", None))
        self.Bouton_rightturn.setShortcut(_translate("IHM", "Right", None))
        self.Bouton_rightshoot.setText(_translate("IHM", "Tirer(Ctrl+Droite)", None))
        self.Bouton_rightshoot.setShortcut(_translate("IHM", "Ctrl+Right", None))
        self.Bouton_rightshift.setText(_translate("IHM", "Pas latéral(Maj+Droite)", None))
        self.Bouton_rightshift.setShortcut(_translate("IHM", "Shift+Right", None))
        self.label_4.setText(_translate("IHM", "Bouger", None))
        self.Bouton_forward.setText(_translate("IHM", "Avancer(Haut)", None))
        self.Bouton_forward.setShortcut(_translate("IHM", "Up", None))
        self.Bouton_back.setText(_translate("IHM", "Reculer(Bas)", None))
        self.Bouton_back.setShortcut(_translate("IHM", "Down", None))
        self.Bouton_crouch.setText(_translate("IHM", "Arrêter(P)", None))
        self.Bouton_crouch.setShortcut(_translate("IHM", "P", None))
        self.label_5.setText(_translate("IHM", "Simulation", None))
        self.Bouton_start.setText(_translate("IHM", "Commencer(C)", None))
        self.Bouton_start.setShortcut(_translate("IHM", "C", None))
        self.Bouton_stop.setText(_translate("IHM", "Stopper(S)", None))
        self.Bouton_stop.setShortcut(_translate("IHM", "S", None))
        self.Bouton_quitter.setText(_translate("IHM", "Quitter(Ctrl+Q)", None))
        self.Bouton_quitter.setShortcut(_translate("IHM", "Ctrl+Q", None))
        self.label_2.setText(_translate("IHM", "Gauche", None))
        self.Bouton_leftturn.setText(_translate("IHM", "Tourner(Gauche)", None))
        self.Bouton_leftturn.setShortcut(_translate("IHM", "Left", None))
        self.Bouton_leftshoot.setText(_translate("IHM", "Tirer(Ctrl+Gauche)", None))
        self.Bouton_leftshoot.setShortcut(_translate("IHM", "Ctrl+Left", None))
        self.Bouton_leftshift.setText(_translate("IHM", "Pas latéral(Maj+Gauche)", None))
        self.Bouton_leftshift.setShortcut(_translate("IHM", "Shift+Left", None))
        self.menuMenu.setTitle(_translate("IHM", "Menu", None))
        self.actionCommencer_Ctrl_C.setText(_translate("IHM", "Commencer (Ctrl+C)", None))
        self.actionCommencer_Ctrl_C.setShortcut(_translate("IHM", "Ctrl+C", None))
        self.actionAide_Ctrl_A.setText(_translate("IHM", "Aide (Ctrl+A)", None))
        self.actionAide_Ctrl_A.setShortcut(_translate("IHM", "Ctrl+A", None))
        self.actionDocumentation_Ctrl_D.setText(_translate("IHM", "Documentation (Ctrl+D)", None))
        self.actionDocumentation_Ctrl_D.setShortcut(_translate("IHM", "Ctrl+D", None))
        self.actionQuitter_Ctrl_Q.setText(_translate("IHM", "Quitter (Ctrl+Q)", None))
        self.actionQuitter_Ctrl_Q.setShortcut(_translate("IHM", "Ctrl+Q", None))

